### ISSUE TITLE
Error 1 

### ISSUE THREAD

**Issue by camarillocorp** [ValentinBV/wialon-php-sdk#1]
HI I tried as in the instructions to eexute the following command with our SID (which is set to expire in one year):
$httpClient = new GuzzleHttp\Client();
$wialonRequest = new valentinbv\Wialon\Request\Action($httpClient);
$wialonRequest->sid='your sid';
try {
    $result = $wialonRequest->execute(
        'core/get_account_data',
        ['type' => 2]
    );
} catch(\Exception  $e) {
    //some action
}

And it returns

Array
(
    [error] => 1
)
{"error":1}

Any idea how can I pass this error please?

**Comment by svix88** [comment]
Hello! I think you are talking about a token that has a lifespan of 1 year. In this request, you need to send the session ID.
For example, https://sdk.wialon.com/wiki/en/sidebar/remoteapi/apiref/errors/errors error code 1 - invalid session.
To get a session, you need to make a request https://sdk.wialon.com/wiki/en/sidebar/remoteapi/apiref/token/login

I made an additional extension for authorization and getting a token and session, maybe it can be useful to you
https://github.com/ValentinBV/wialon-php-oauth

To get a session using a token, use the https://github.com/ValentinBV/wialon-php-oauth/blob/master/src/WialonOAuth/OAuthClient.php#L143 method
An example is described on the extension page
https://github.com/ValentinBV/wialon-php-oauth

`if ($_GET['access_token']) {
    $httpClient = new GuzzleHttp\Client();
    $auth = new valentinbv\WialonOAuth\OAuthClient($httpClient);
    try {
        $auth->setToken($_GET['access_token']);
        $result = $auth->login();
    } catch(\Exception $e) { 
        echo $e->getMessage();
    }
}`

**Comment by camarillocorp** [comment]
Thanks for your response. I was able to create my own solution in a class, because other issues arised (composer version, guzzle not installing correctly, lack of documentation, etc. Now I can query anything from the remote api.

Have a nice day!
